### ISSUE TITLE
Implement the features configured by json.loads kwargs

### ISSUE THREAD

**Issue by KOLANICH** [dpranke/pyjson5#12]

**Comment by dpranke** [comment]
Will do :).

**Comment by dpranke** [comment]
I've now implemented support for the object_hook and object_pairs_hook (as of e23b7aaf).

**Comment by dpranke** [comment]
And, now I've implemented the rest as of e3c78fdf, except for the `cls` argument, which doesn't make any sense in this implementation (there's no JSONDecoder class).

**Comment by KOLANICH** [comment]
Thank you.

**Comment by dpranke** [comment]
You're welcome :).
