### ISSUE TITLE
Simplejson compatibility  (object_pairs_hook & object_hook)

### ISSUE THREAD

**Issue by cavanaug** [dpranke/pyjson5#17]
I may take a run at implementing this one myself.   

Basically we would like the ability to preserve key ordering similarly to how simplejson does this with the object_pairs_hook.    

We dont need the the object_hook which is more for jsonrpc, but might be nice for on the fly schema validation in the future for us.

**Comment by dpranke** [comment]
I've implemented both in e23b7aaf .
