### ISSUE TITLE
pyjson5 cli not working (at least on python3)

### ISSUE THREAD

**Issue by cavanaug** [dpranke/pyjson5#19]
Seems to be missing the options etc

└──>> pyjson5 -h
usage: pyjson5 [-h] [-V]

optional arguments:
  -h, --help     show this help message and exit
  -V, --version  Print the version and exit.

└──>> pyjson5
Traceback (most recent call last):
  File "/usr/local/bin/pyjson5", line 9, in <module>
    load_entry_point('json5==0.5.0', 'console_scripts', 'pyjson5')()
  File "/usr/local/lib/python3.5/dist-packages/json5-0.5.0-py3.5.egg/json5/main.py", line 41, in main
    if args.cmd:

**Comment by dpranke** [comment]
Bah, I forgot about the wrapper script. Will fix ASAP.

**Comment by dpranke** [comment]
This should be fixed in e0a53da.

**Comment by dpranke** [comment]
I've pushed this to PyPI as v0.5.1.
