### ISSUE TITLE
Does not parse hex literals longer than 2 digits

### ISSUE THREAD

**Issue by svenstucki** [dpranke/pyjson5#2]
Looking at the grammar this seems clear. It would be nice to have though and I can't fix it myself, so consider this a feature request :).

Minimal example:

    json5.loads("{a:0xabc}")

yields:

    Exception: :1:1 expecting '0X'

**Comment by dpranke** [comment]
You're absolutely right. It's fixed now, in https://github.com/dpranke/pyjson5/commit/634e9a .

I've pushed out a new version with a fix as well (v0.2.3).

Thanks for the report!
