### ISSUE TITLE
Duplicate keys

### ISSUE THREAD

**Issue by ololoe** [dpranke/pyjson5#24]
json5 is intended for usage as config. `configparser` raises an Exception on duplicate keys

`configparser.DuplicateOptionError: While reading from 'file' [line xxx]: option 'yyy' in section 'zzz' already exists`

I think it's worse adding this as an option or even as default.

**Comment by dpranke** [comment]
I'm not 100% sure I understand what you're asking for.

You're asking for an option to check for duplicate keys to be added to json5.load() and json5.loads(), right? Something like an `allow_duplicates` flag that defaulted to True, but if set to False, would cause an exception to be raised like configparser does w/ the `strict` option?

If so, I think this is a reasonable suggestion. 

As a possible workaround in the meantime, the json5 implementation supports the object_hook and object_pairs_hook hooks, so you can implement your own custom behavior a la https://stackoverflow.com/questions/14902299/json-loads-allows-duplicate-keys-in-a-dictionary-overwriting-the-first-value to get duplicate key checking now, if that helps.

But, this seems like a straightforwardly useful thing to me to add even if the stock json library doesn't support this.

**Comment by dpranke** [comment]
Well, you never replied, so I'm assuming I was right :).

I've added an allow_duplicate_keys flag to v0.8.2 (4ad75d46cd8aee28d23e3887dd756b781ffb352d).
