### ISSUE TITLE
Packaging license file

### ISSUE THREAD

**Issue by jakirkham** [dpranke/pyjson5#25]
It would be good to include the license file in `sdist`s or wheels on PyPI and any other packages. This can be done by adding a [`MANIFEST.in` with a line like this]( https://github.com/pypa/sampleproject/blob/cbabca3f3f54a6e053e231d4cc89a46550049107/MANIFEST.in#L4-L5 ) and a [`setup.cfg` with this line]( https://github.com/pypa/sampleproject/blob/cbabca3f3f54a6e053e231d4cc89a46550049107/setup.cfg#L1-L4 ).

**Comment by dpranke** [comment]
Thanks for the request. I can certainly add this, and I'll try to do so today.

**Comment by dpranke** [comment]
Fixed in 6c4038e449e2083f1f09328a1f92cbe702607dea (v0.8.5).
