### ISSUE TITLE
Identifiers starting with a reserved keyword are treated as reserved keywords

### ISSUE THREAD

**Issue by yohummus** [dpranke/pyjson5#29]
First of all, thank you for this great library!

I noticed that `dump()` puts quotes around identifiers that only start with a reserved keyword. For example: `internal_parameter` would be dumped as `"internal_parameter"`.

The issue seems to be in the regex that is created in `lib._is_reserved_word()`. Just appending `$` to the whole pattern so that it reads `_reserved_word_re = re.compile('|'.join(['break', ..., 'with']) + '$')` fixes it.

**Comment by dpranke** [comment]
I apologize for the delay in getting to this. You're right, it's a bug, and I'll try to get a patch posted shortly.

**Comment by dpranke** [comment]
Okay, this should be fixed now in [v0.9.0](https://github.com/dpranke/pyjson5/tree/v0.9.0), which is [live on PyPI](https://pypi.org/project/json5/0.9.0/).
