### ISSUE TITLE
Does not support underscore and $ in identifiers

### ISSUE THREAD

**Issue by svenstucki** [dpranke/pyjson5#3]
The grammar for identifiers is wrong:

    ident = ident_start:hd (letter|digit)*:tl -> ''.join([hd] + tl),

    ident_start = (letter|'$'|'_'):i -> i,

It only allows '$' and '_' at the start, but according to [this](https://developer.mozilla.org/en-US/docs/Glossary/Identifier) they should be allowed afterwards too.

By the way, thanks for fixing the last issue so fast.

**Comment by dpranke** [comment]
Right again. I've pushed a new version (v0.2.4) that fixes this.

The code does not support unicode letter classes or unicode escape sequences in unquoted object keys yet (I filed separate bugs and updated the docs). Let me know if that's a problem.

**Comment by svenstucki** [comment]
No, that's fine for me. Thanks for fixing it.

By the way, what tool do you use for grammar to code conversion?

**Comment by dpranke** [comment]
The compiler-compiler is my 'glop' project, which is a PEG-based thing
written in Python that I've been working on off-and-on for a while. It's
very immature and undocumented, but I'm hoping to clean it up substantially
over the next few weeks.

-- Dirk

**Comment by svenstucki** [comment]
Yes, I immediately read your commit message after the post. Seems quite useful already! I don't have much experience with automatic parser generators, that's why I was curious.
