### ISSUE TITLE
sample.json5 missing

### ISSUE THREAD

**Issue by PromyLOPh** [dpranke/pyjson5#31]
[This test](https://github.com/dpranke/pyjson5/blob/6c4038e449e2083f1f09328a1f92cbe702607dea/tests/lib_test.py#L159) references a file called sample.json5, which does not exist in the repository and therefore fails to execute.

**Comment by dpranke** [comment]
Thanks for reporting this, and I'm sorry for not responding sooner. I'll take a look.

**Comment by dpranke** [comment]
Sorry for the delay in replying ...

Looking at this now, I'm confused. sample.json5 should exist [at the top of the repo](https://github.com/dpranke/pyjson5/blob/master/sample.json5), at least on the master branch. 

Do you not have that in your checkout? Maybe you're on a different branch?

**Comment by PromyLOPh** [comment]
You’re right, I was looking at the source code tarball at [pypi.org](https://pypi.org/project/json5/#files) and not the repository. That one includes tests, but lacks sample.json5, thus testing failed. My bad.

**Comment by dpranke** [comment]
Great, no problem.
