### ISSUE TITLE
json5.dump to stdout does not pretty-print

### ISSUE THREAD

**Issue by simonseyock** [dpranke/pyjson5#39]
If I use `json5.dump` with the `indent` parameter to write directly to stdout it does not pretty print. If I output to a file it works. This diverges from the behavior of `json.dump`.

Example program:

```python
import json
import json5
from sys import stdout

data = {
    'test': 3,
    'more': 'stuff'
}

stdout.write('json.dump: \n')
json.dump(data, stdout, indent=2)
stdout.write('\njson5.dump: \n')
json5.dump(data, stdout, indent=2)
stdout.write('\njson5.dumps: \n')
stdout.write(json5.dumps(data, indent=2))
stdout.write('\n')
```

Output:

```
json.dump: 
{
  "test": 3,
  "more": "stuff"
}
json5.dump: 
{"test": 3, "more": "stuff"}
json5.dumps: 
{
  test: 3,
  more: "stuff",
}
```

**Comment by simonseyock** [comment]
I forget to check if this does not occur in the newest version. I use 0.9.2 at the moment.

**Comment by simonseyock** [comment]
I tested it with 0.9.4 and it does work correctly. Nevermind this issue then.

**Comment by dpranke** [comment]
Thanks for the report. I haven't tried to reproduce this to be sure, but I expect this was fixed by 6de83c.
