### ISSUE TITLE
ZeroDivisionError in benchmarks

### ISSUE THREAD

**Issue by spyoungtech** [dpranke/pyjson5#42]
It seems that on the ios-simulator.json I can manage to get json_time of `0.0` causing the performance calculations to error out.

I "fixed" locally by using `(json_time or 0.0005)` not sure if that's reasonable or not. Just thought I'd bring it up here.

**Comment by dpranke** [comment]
That would be one way to do it. Another way would be to just handle the cases when the times are zero differently. I'll probably change it to something like the latter.

**Comment by dpranke** [comment]
This should be fixed now (the output is quite different, though).

Thanks for reporting it!
