### ISSUE TITLE
builds fails on raspberry pi 4 due to usage of __int128

### ISSUE THREAD

**Issue by chatumao** [dpranke/pyjson5#43]
I'm not an expert on C++, but as far as I can tell the build fails on the pi because the compiler doesn't support the __int128 type. I read that this type should not even be used because of portability problems, so the question is if it will be changed at some point. Is it really necessary to use such a large data type for parsing?

**Comment by dpranke** [comment]
Hi!

I'm not sure if you're reporting an issue on the right project; pyjson5 is pure Python and there's no build for it.

We're you maybe looking for https://github.com/Kijewski/pyjson5 instead?

If not, can you give me more information on what you're seeing?

**Comment by chatumao** [comment]
Yes you are indeed right, wrong project. I realized the difference in authors but thought you had taken over the project because of the same name. Anyways, would it be possible to install your project as a module from within a python script?

**Comment by dpranke** [comment]
I'm sorry, I don't know what you mean by "install your project as a module from within a python script"?

Can you go into more detail about what you're trying to do?

This package is published on PyPI (it's the 'json5' module there), so, maybe, yes?

**Comment by chatumao** [comment]
Yes, that's what I meant. I replaced pyjson5 with your module and it works fine in my scripts as far as I can tell. Thanks a lot for your help and your efforts!

**Comment by dpranke** [comment]
Great, glad it works for you. :).
