### ISSUE TITLE
Control formatting with `dump` / `dumps`

### ISSUE THREAD

**Issue by alexreg** [dpranke/pyjson5#48]
Is there any way to control JSON5 aspects of formatting when using `dump` / `dumps`? For example, whether to quote key names of objects, or whether to include trailing commas.

**Comment by dpranke** [comment]
It's a bit harder for me to picture trailing_commas_array or a conditional quote_keys to be useful: personally it feels like that would encourage stylistic inconsistencies. So, I wouldn't be inclined to add them just for the sake of things.

But, if someone comes up with convincing real-world examples of where they'd be useful, I could be convinced :).

**Comment by dpranke** [comment]
Yes, it should quote keys with spaces properly. I could imagine a single/double quote flag to be useful, though.
