### ISSUE TITLE
Hex in generated json

### ISSUE THREAD

**Issue by omasoud** [dpranke/pyjson5#49]
json5 allows numbers to be have hexadecimal representation, but can it generate hexadecimal numbers (via dump/dumps)?

**Comment by dpranke** [comment]
Not currently, no.

**Comment by dpranke** [comment]
I'm going to close this, as hopefully the question was answered. 

I'm not against implementing this in principle, but in practice it's not obvious to me how one would do this without either adding a flag to dump *all* numbers in hex (and it is not obvious how useful that would be) or having some way to dump things field-by-field, at which point you're probably better off writing your own `dump`-like function.

I can also sort of imagine a way one might implement this on top of a more powerful api/implementation like what we'd need to preserve comments (see issue #28): such an implementation could probably also preserve whether the number was decimal or hex and render the value back out in the same format.
