### ISSUE TITLE
`dumps` with `default` function specified returns dict instead of str

### ISSUE THREAD

**Issue by alexreg** [dpranke/pyjson5#50]
This is a minimal reproducible example, illustrating the unexpected behaviour of `json5.dumps` (and also how `json.dumps` behaves correctly here).

```
import json
import json5


class Foo:
	pass


def foo_default(obj):
	if isinstance(obj, Foo):
		return { "foo": "bar" }
	
	raise TypeError()


json.dump(Foo(), default = foo_default) # GOOD: returns str
json5.dumps(Foo(), default = foo_default) # BAD: returns dict!
```

It seems that `json5.dumps` is behaving quite differently to `json.dumps`, and expecting the `default` fn to return a *str* (i.e. pre-serialized object), not merely a *serializable* object.

**Comment by dpranke** [comment]
This was fixed in 50898a4
