### ISSUE TITLE
Unreadable error message

### ISSUE THREAD

**Issue by ololoe** [dpranke/pyjson5#6]
```
json5.loads('')
Exception: :1:1 expecting '0X'
```

Even builtin json decoder (which isn't very informative) gives better error message

```
json.loads('')
ValueError: No JSON object could be decoded
```

**Comment by dpranke** [comment]
Yeah, I can definitely do better here. I'll see if I can patch this in the next day or two.

**Comment by dsever** [comment]
Hi, 

I have the same problem, is there any patch for this or kind of workaround.

Thanks 
Dubravko

**Comment by dpranke** [comment]
Okay, this fell off my radar. Hopefully I can get to this soon.

In the meantime, as a workaround, why not check for an empty string prior to calling json5.loads() ?

**Comment by Eliont** [comment]
What i found so far - :1:1 expecting '0X'  error can be in such cases:
1) on encounter "!" symbol
2) on numeric key
3) empty or totally invalid source code

**Comment by dpranke** [comment]
This should be better in the latest commit, 3cb64842, which I've tagged with `v0.3`. I will do another release to PyPI once I've done a bit more testing and fixed a couple more issues, hopefully in a couple days.
