### ISSUE TITLE
AttributeError: 'module' object has no attribute 'inf'

### ISSUE THREAD

**Issue by rqx110** [dpranke/pyjson5#60]
Python 2.7.18

after upgrade to latest version v0.9.10,

```py
import json5
import codecs

config = {"foo": 'bar'}
with codecs.open('config1.json', 'w', encoding='utf-8') as f:
    json5.dump(config, f, indent=4, quote_keys=True, trailing_commas=False, ensure_ascii=False)
```

an error occurred as title

**Comment by dpranke** [comment]
Whoops, sorry about that. v0.9.10 requires Python 3. I forgot to make that clear in the release notes. I will fix that soon.

**Comment by rqx110** [comment]
it looks like 0.9.9 is already requires Python 3. see https://github.com/dpranke/pyjson5/commit/1f7f8062a76d5899288674b938e73b7bcadf63c3

**Comment by dpranke** [comment]
Hmm. You might be right, I think I got that change confused with something else. Good news is that maybe I can go back to supporting Python 2.

I'll try to check on these things in the next day or two.
