### ISSUE TITLE
no pretty printing?

### ISSUE THREAD

**Issue by philiparvidsson** [dpranke/pyjson5#69]
a = {"foo": 2}
    print(pyjson5.dumps(a, indent=2))

does not pretty-print.

**Comment by dpranke** [comment]
*Finally* getting to this; apologies for the delay!

Your example works fine for me:

```
$ python3
>>> import json5
>>> json5.VERSION
'0.9.14'
>>> a = {"foo": 2}
>>> print(json5.dumps(a, indent=2))
{
  foo: 2,
}
>>>
```

Were you seeing something different?

**Comment by dpranke** [comment]
Closing as there's been no response.
