### ISSUE TITLE
Question: is this code effected by CVE: GHSA-9c47-m6qq-7p4h

### ISSUE THREAD

**Issue by debasishbsws** [dpranke/pyjson5#72]
GHSA-9c47-m6qq-7p4h

**Comment by dpranke** [comment]
No, I don't believe this library is affected by that bug. Specifically, that bug refers to a Javascript library
and Javascript's prototypical inheritance. Python does not really have an equivalent and I don't believe there are keys that you can set on an object that will escape the item's namespace.

Thanks for checking, though! While I was pretty sure this was true, I had to play with things for a while to make sure I couldn't replicate something like the bug. I suppose it's possible that I've missed something, but if so, I'm not sure what I missed.

**Comment by debasishbsws** [comment]
For some reason, Grype scanner is picking this CVE in this application (it may be a false positive), Thanks for investigating though.
