### ISSUE TITLE
Multikey dictionary support?

### ISSUE THREAD

**Issue by commonuserlol** [dpranke/pyjson5#79]
Hello, thanks for this library, i have json like {"a": 1, "a": 2, "a": 3}, but parsing gives only one of them, can you add support for multikey dict (so will be 3 keys "a" and values for them in range 1-3)?

**Comment by dpranke** [comment]
Hi! I'm glad you found it, and hopefully it's helpful :).

I think you can maybe get something close to what you want using the `object_pairs_hook` parameter:

```
$ cat t.py
import json5

def repeated_keys(pairs):
    d = {}
    for k, v in pairs:
        d.setdefault(k, []).append(v)
    for k in d.keys():
        if len(d[k]) == 1:
            d[k] = d[k][0]
    return d

o = json5.loads('{a: 1, a: 2, a: 3, b: 1}', object_pairs_hook=repeated_keys)
print(o)
$ python t.py
{'a': [1, 2, 3], 'b': 1}
$
```

If that's not what you were going for, let me know and we can see if we can come up with something else. I can imagine a couple of other variants that might be what you were looking for if the above wasn't it. The `object_pairs_hook` and `object_hook` parameters should give you a pretty wide range of options.

**Comment by commonuserlol** [comment]
Thanks, this is exactly what I was looking for

**Comment by dpranke** [comment]
Great, glad it worked for you :).
