### ISSUE TITLE
Which extension should json5 files have?

### ISSUE THREAD

**Issue by ololoe** [dpranke/pyjson5#8]
^^

**Comment by dpranke** [comment]
I don't know that there's a particular standard for this. I'd probably use .json5 :).

**Comment by ploxiln** [comment]
from https://github.com/aseemk/json5

> JSON5 is not an official successor to JSON, and JSON5 content may not work with existing JSON parsers. For this reason, JSON5 files use a new .json5 extension. (TODO: new MIME type needed too.)
